# Generated by Django 6.1.1 on 2026-09-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='voice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('voice_id', models.CharField(max_length=100, unique=True)),
                ('gender', models.CharField(max_length=100)),
            ],
        ),
    ]
