# Generated by Django 6.1.1 on 2026-09-24 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textaudio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voice',
            name='gender',
        ),
    ]
