# Generated by Django 6.1.1 on 2026-09-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textaudio', '0002_remove_voice_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='voice',
            name='gender',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
